/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as BlocksBlockRouteImport } from './routes/blocks.$block'
import { Route as BlocksBlockIndexRouteImport } from './routes/blocks.$block.index'
import { Route as ViewStyleNameNameRouteImport } from './routes/view.$styleName.$name'
import { Route as OgDocsSplatRouteImport } from './routes/og.docs.$'
import { Route as BlocksBlockPreviewRouteImport } from './routes/blocks.$block.preview'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlocksRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const BlocksBlockRoute = BlocksBlockRouteImport.update({
  id: '/$block',
  path: '/$block',
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksBlockIndexRoute = BlocksBlockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlocksBlockRoute,
} as any)
const ViewStyleNameNameRoute = ViewStyleNameNameRouteImport.update({
  id: '/view/$styleName/$name',
  path: '/view/$styleName/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => OgRoute,
} as any)
const BlocksBlockPreviewRoute = BlocksBlockPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => BlocksBlockRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRouteWithChildren
  '/blocks/$block': typeof BlocksBlockRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/blocks/': typeof BlocksIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/blocks/$block/preview': typeof BlocksBlockPreviewRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/view/$styleName/$name': typeof ViewStyleNameNameRoute
  '/blocks/$block/': typeof BlocksBlockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/blocks': typeof BlocksIndexRoute
  '/docs': typeof DocsIndexRoute
  '/blocks/$block/preview': typeof BlocksBlockPreviewRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/view/$styleName/$name': typeof ViewStyleNameNameRoute
  '/blocks/$block': typeof BlocksBlockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRouteWithChildren
  '/blocks/$block': typeof BlocksBlockRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/blocks/': typeof BlocksIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/blocks/$block/preview': typeof BlocksBlockPreviewRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/view/$styleName/$name': typeof ViewStyleNameNameRoute
  '/blocks/$block/': typeof BlocksBlockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/docs'
    | '/llms.txt'
    | '/og'
    | '/blocks/$block'
    | '/docs/$'
    | '/blocks/'
    | '/docs/'
    | '/blocks/$block/preview'
    | '/og/docs/$'
    | '/view/$styleName/$name'
    | '/blocks/$block/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/og'
    | '/docs/$'
    | '/blocks'
    | '/docs'
    | '/blocks/$block/preview'
    | '/og/docs/$'
    | '/view/$styleName/$name'
    | '/blocks/$block'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/docs'
    | '/llms.txt'
    | '/og'
    | '/blocks/$block'
    | '/docs/$'
    | '/blocks/'
    | '/docs/'
    | '/blocks/$block/preview'
    | '/og/docs/$'
    | '/view/$styleName/$name'
    | '/blocks/$block/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgRoute: typeof OgRouteWithChildren
  ViewStyleNameNameRoute: typeof ViewStyleNameNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blocks/$block': {
      id: '/blocks/$block'
      path: '/$block'
      fullPath: '/blocks/$block'
      preLoaderRoute: typeof BlocksBlockRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/blocks/$block/': {
      id: '/blocks/$block/'
      path: '/'
      fullPath: '/blocks/$block/'
      preLoaderRoute: typeof BlocksBlockIndexRouteImport
      parentRoute: typeof BlocksBlockRoute
    }
    '/view/$styleName/$name': {
      id: '/view/$styleName/$name'
      path: '/view/$styleName/$name'
      fullPath: '/view/$styleName/$name'
      preLoaderRoute: typeof ViewStyleNameNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof OgRoute
    }
    '/blocks/$block/preview': {
      id: '/blocks/$block/preview'
      path: '/preview'
      fullPath: '/blocks/$block/preview'
      preLoaderRoute: typeof BlocksBlockPreviewRouteImport
      parentRoute: typeof BlocksBlockRoute
    }
  }
}

interface BlocksBlockRouteChildren {
  BlocksBlockPreviewRoute: typeof BlocksBlockPreviewRoute
  BlocksBlockIndexRoute: typeof BlocksBlockIndexRoute
}

const BlocksBlockRouteChildren: BlocksBlockRouteChildren = {
  BlocksBlockPreviewRoute: BlocksBlockPreviewRoute,
  BlocksBlockIndexRoute: BlocksBlockIndexRoute,
}

const BlocksBlockRouteWithChildren = BlocksBlockRoute._addFileChildren(
  BlocksBlockRouteChildren,
)

interface BlocksRouteChildren {
  BlocksBlockRoute: typeof BlocksBlockRouteWithChildren
  BlocksIndexRoute: typeof BlocksIndexRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksBlockRoute: BlocksBlockRouteWithChildren,
  BlocksIndexRoute: BlocksIndexRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface OgRouteChildren {
  OgDocsSplatRoute: typeof OgDocsSplatRoute
}

const OgRouteChildren: OgRouteChildren = {
  OgDocsSplatRoute: OgDocsSplatRoute,
}

const OgRouteWithChildren = OgRoute._addFileChildren(OgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgRoute: OgRouteWithChildren,
  ViewStyleNameNameRoute: ViewStyleNameNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
